config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  delete '/logout' => 'sessions#destroy', as: :logout
  resources :users
  resources :meetings
  resources :sessions, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
   has_secure_password
   has_many :meetings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end 

  def logged_in?
    !!current_user
  end 

  def authorize
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authorize_meeting_view, only: :edit
  before_action :authorize, only: [:show]

  def index
    @meetings = Meeting.all
    
  end

  def show
    @meeting = Meeting.find(params[:id])
    @user = User.find @meeting.user_id
  end

  def new
    @meeting = current_user.meetings.new
  end

  def create
    @meeting = current_user.meetings.new meetings_params
    @meeting.save
    redirect_to meeting_path @meeting.id
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end

  def update
    @meeting = Meeting.find(params[:id])
    if @meeting.update(meetings_params)
      redirect_to meeting_path
    else
      redirect_to meeting_path(@meeting.id)
    end 
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
    redirect_to "/"
  end

  def authorize_meeting_view
    @meeting = Meeting.find(params[:id])
    if @meeting.user_id != current_user.id
      redirect_to meetings_path
    end
  end 

  private
  def meetings_params
    return params.require(:meeting).permit(:name, :address)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id 
      redirect_to user_path(@user)
    else
      flash[:warning] = "Check your email and password"
      redirect_to new_session_path
    end 
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_current_user, only: [:show]
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path @user.id
    else
      flash[:warning] = "Check your email and password"
      redirect_to new_user_path
    end
  end

  def edit
    
  end

  def update
  end

  def destroy
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 
  def verify_current_user
    redirect_to user_path(current_user.id) unless params[:id].to_i == current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AAroundLA</title>
    <%= csrf_meta_tags %>
    
    <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/flash" %>
    <%= render "/partials/nav" %>
    
    <%= yield %>
    
    <!-- <div class="footer">
      <p>Created by EM</p>
    </div> -->

  </body>
</html>

app/views/meetings/create.html.erb
<h1>Meetings#create</h1>
<p>Find me in app/views/meetings/create.html.erb</p>

app/views/meetings/destroy.html.erb
<h1>Meetings#destroy</h1>
<p>Find me in app/views/meetings/destroy.html.erb</p>

app/views/meetings/edit.html.erb
<%= render "/partials/form" %>

app/views/meetings/index.html.erb
<h1>Find AA Meeting</h1>

<% @meetings.each do |m| %>
    <li><%= link_to("#{m.name}, #{m.address}", meeting_path(m.id)) %></li>
<% end %>

app/views/meetings/new.html.erb
<h1>Add AA Meeting!</h1>
      
<%= render "/partials/form" %>


        

app/views/meetings/show.html.erb
<!-- <h4>Thank you for your contribution!</h4> -->
<% if !logged_in? %>
    <% redirect_to new_session_path %>
<% end %>

<h1><%= @meeting.name %></h1>
<h2><%= @meeting.address %></h2>
<iframe id="google-maps"
  width="400"
  height="400"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDYzCYV-ftuNMqm6oKfaG0ZmTjOrbDU08c&q=<%= @meeting.address %>" allowfullscreen>
</iframe>
<br>
<%# check to see if meeting was created by the current user. if so, show an edit button %>
<% if @meeting.user == current_user %>
    <%= link_to "Edit Meeting", edit_meeting_path(@meeting.id) %>
    ||
    <%# link_to "Delete Meeting", meeting_path(@meeting.id), {method: 'delete'} %> 
    <span id="modal" data-toggle="modal" data-target="#exampleModal">Delete Meeting</span>
<% end %>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Meeting</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this meeting?
            </div>
            <div class="modal-footer">
                <%= link_to "Yes", meeting_path(@meeting.id), {method: 'delete'} %> 
            </div>
          </div>
        </div>
      </div>
      
<!-- AIzaSyDYzCYV-ftuNMqm6oKfaG0ZmTjOrbDU08c -->

app/views/meetings/update.html.erb
<h1>Meetings#update</h1>
<p>Find me in app/views/meetings/update.html.erb</p>

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>">
    <%= value %>
</div>    
<% end %>

app/views/partials/_form.html.erb
<%= form_for @meeting do |f| %>
    <div class="form-group">
        <label for="meetingName">Meeting Name</label>
        <%= f.text_field :name, class: "form-control", placeholder: "Meeting Name" %>
    </div>

    <div class="form-group">
        <label for="meetingAddress">Meeting Address</label>
        <%= f.text_field :address, class: "form-control", placeholder: "Address, City, State, Zip" %>   
    </div>
        <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/partials/_nav.html.erb
<div id="navbar">
    <ul>
        <% if logged_in? %>
            <li><%= link_to "Logout", logout_path, {method: "DELETE"} %></li>
            <li><%= link_to "Add Meetings", new_meeting_path %></li>    
            <li><%= link_to "Profile", user_path(current_user.id) %></li>
        <% else %>
            <li><%= link_to("Sign Up", "/users/new") %></li>
            <li><%= link_to "Login", new_session_path %></li>
        <% end %>     
            <li><%= link_to "Browse Meetings", meetings_path %></li> 
            <li><%= link_to("HOME", "/") %></li>
    </ul>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>AAroundLA</h1>
<br>
    <div id="accordion">
            <div class="card">
              <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                  <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    The Mission
                  </button>
                </h5>
              </div>
          
              <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    Make the quickest and easiest way to look up and find an AA meeting close to you. Going to meetings and meeting others in the program are key to laying a solid foundation on your road to recovery.
                </div>
              </div>
            </div>
            <div class="card">
              <div class="card-header" id="headingTwo">
                <h5 class="mb-0">
                  <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Want to Help?
                  </button>
                </h5>
              </div>
              <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                <div class="card-body">
                    It's easy and it's free! Just sign up and add a meeting to the directory. Find a meeting and help others find meetings in their area.  
                </div>
              </div>
            </div>
            <div class="card">
              <div class="card-header" id="headingThree">
                <h5 class="mb-0">
                  <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Future Applications
                  </button>
                </h5>
              </div>
              <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                <div class="card-body">
                    Give people a way to review and rate AA meetings they have attended.<br>Users who sign up, can message each other.<br>Expand the scope of the project to other major cities.<br>Add a sobreity calculator.
                </div>
              </div>
            </div>
        </div>

app/views/users/new.html.erb
<div class="row">
        <div class="col-md-6 offset-md-3">
          <h1>Sign Up</h1>
          <%= form_for @user do |f| %>
            <div class="form-group">
              <label>Name</label>
              <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
            </div>
            <div class="form-group">
              <label>Email</label>
              <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
              <small id="emailHelp" class="form-text text-muted"></small>
            </div>
            <div class="form-group">
              <label>Password</label>
              <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
            </div>
            <div class="form-group">
              <label>Confirm Password</label>
              <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
            </div>
            <%= f.submit "Create AAccount", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %>!</h1>
<h4>Meetings you have added:</h4>
<ul>
    <% @user.meetings.each do |m| %>
        <li><%= link_to(m.name, meeting_path(m.id)) %></li>
    <% end %>
</ul>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>